# Generated by Django 5.1.1 on 2024-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('code', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('status', models.CharField(default='pending', max_length=12)),
                ('phone', models.CharField(default='null', max_length=12)),
            ],
        ),
    ]
