# Generated by Django 4.2.7 on 2025-01-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phonenumber',
        ),
    ]
