# Generated by Django 4.2.7 on 2025-01-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_helpdeskticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskticket',
            name='replied',
            field=models.BooleanField(default=False),
        ),
    ]
