# Generated by Django 5.1.1 on 2024-09-28 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_delete_student'),
        ('teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('reg_no', models.CharField(max_length=6)),
                ('grade', models.CharField(max_length=20)),
                ('admission_no', models.CharField(max_length=20)),
                ('section', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
                ('address', models.TextField()),
                ('teacherid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
