# Generated by Django 4.2.7 on 2024-12-07 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_descriptive'),
        ('student', '0004_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('mcq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.mcq')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
