# Generated by Django 4.2.7 on 2024-12-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_descriptive'),
        ('student', '0005_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescriptiveAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('descriptive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.descriptive')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
