# Generated by Django 4.2.7 on 2024-12-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_descriptiveanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_left', models.IntegerField(default=100)),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
