# Generated by Django 4.2.7 on 2024-12-11 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_remove_clock_title_clock_exam_clock_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='student',
            new_name='students',
        ),
    ]
