# Generated by Django 4.2.7 on 2024-12-11 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rename_student_clock_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='exam',
            new_name='exams',
        ),
    ]
