# Generated by Django 4.2.7 on 2024-12-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_exam_clock_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='time_left',
            field=models.IntegerField(default=1.0),
        ),
    ]
