# Generated by Django 4.2.7 on 2024-12-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_descriptiveanswer_marks_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='marks_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
