# Generated by Django 4.2.7 on 2024-12-13 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_exam_minimum_alter_exam_marks_alter_exam_sub'),
        ('student', '0013_studentanswer_marks_awarded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.PositiveIntegerField(default=0)),
                ('pass_status', models.BooleanField(default=False)),
                ('exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
