# Generated by Django 4.2.7 on 2025-01-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_totalresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TotalResult',
        ),
    ]
