# Generated by Django 5.0.7 on 2025-02-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
