# Generated by Django 5.0.7 on 2025-02-25 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_student_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacherid',
        ),
    ]
