# Generated by Django 5.0.7 on 2025-02-25 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_helpdeskticket_replied'),
        ('student', '0019_remove_student_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.institute'),
        ),
    ]
