# Generated by Django 5.0.6 on 2025-02-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='time_start',
            field=models.DateTimeField(),
        ),
    ]
