# Generated by Django 5.0.6 on 2025-02-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_alter_clock_time_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clock',
            name='time_left',
            field=models.FloatField(default=1.0),
        ),
    ]
