# Generated by Django 5.1.1 on 2024-09-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_qualification1_remove_principal_qualification_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qualification1',
            new_name='qualificationP',
        ),
    ]
