# Generated by Django 5.1.1 on 2024-09-07 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='qualification1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='teacher1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teaching_sub', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('exp', models.CharField(max_length=10)),
                ('grade', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('tid', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teacher/')),
                ('principalid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.principal')),
                ('qualificationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.qualification1')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
