# Generated by Django 5.0.7 on 2024-11-02 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('start', models.TimeField()),
                ('duration', models.CharField(max_length=100)),
                ('marks', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('discp', models.CharField(max_length=200)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher1')),
            ],
        ),
    ]
