# Generated by Django 5.0.7 on 2024-11-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='sub',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
