# Generated by Django 4.2.7 on 2024-12-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_alter_exam_duration_examattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='minimum',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='sub',
            field=models.CharField(max_length=200),
        ),
    ]
