# Generated by Django 4.2.7 on 2024-12-16 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_exam_minimum_alter_exam_marks_alter_exam_sub'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examattempt',
            old_name='exam',
            new_name='exams',
        ),
    ]
