# Generated by Django 5.0.7 on 2025-01-11 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_teacher1_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher1',
            name='status',
        ),
        migrations.AddField(
            model_name='exam',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
