# Generated by Django 5.0.7 on 2025-02-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0015_remove_teacher1_status_exam_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher1',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
