# Generated by Django 5.0.7 on 2025-02-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_teacher1_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher1',
            name='principalid',
        ),
    ]
