# Generated by Django 5.0.7 on 2025-02-25 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_helpdeskticket_replied'),
        ('teacher', '0017_remove_teacher1_principalid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher1',
            name='institute',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='common.institute'),
        ),
    ]
