# Generated by Django 5.0.6 on 2025-02-28 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0018_teacher1_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='number_of_questions',
            field=models.IntegerField(default=1),
        ),
    ]
